From jupyter/scipy-notebook

RUN pip install scikit-learn
RUN pip install tensorflow
RUN pip install xgboost
RUN pip install nltk 
RUN pip install gensim
RUN pip install keras
RUN pip install bokeh  

